repos:
  - repo: local
    hooks:
      - id: lint
        name: lint
        entry: nox -rs lint --
        language: system
        types: [python]
        files: "^pytket/.+|^tests/.+|noxfile.py"
      - id: mypy
        name: mypy
        entry: nox -rs type_checking --
        language: system
        types: [python]
        files: "^pytket/.+|^tests/.+|noxfile.py"
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.6.0
    hooks:
      - id: prettier
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
