name: All checks
run-name: "[${{ github.ref_name }}] All checks"

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - develop
  schedule:
    # 04:00 every Tuesday morning
    - cron: "0 4 * * 2"

jobs:
  tests:
    name: Run ${{ matrix.session }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { python: "3.10", os: "ubuntu-22.04", session: "pre-commit" }
          - { python: "3.10", os: "macos-12", session: "mypy" }
          - { python: "3.10", os: "windows-2022", session: "tests" }
          - { python: "3.10", os: "ubuntu-22.04", session: "tests" }
          - { python: "3.10", os: "macos-12", session: "tests" }
          - { python: "3.11", os: "windows-2022", session: "tests" }
          - { python: "3.11", os: "ubuntu-22.04", session: "tests" }
          - { python: "3.11", os: "macos-12", session: "tests" }
          - { python: "3.10", os: "ubuntu-22.04", session: "docs-build" }
    uses: ./.github/workflows/nox-session.yml
    with:
      python-version: ${{ matrix.python }}
      os: ${{ matrix.os }}
      nox-session: ${{ matrix.session }}
